### ISSUE TITLE
Update pygobject dependency

### ISSUE THREAD

**Issue by ashkitten** [eigengrau/x-highlight-region#7]
as far as i can tell, it seems to work with `pygobject==3.28.3`, and `pygobject<3.27` is not on pip anymore so it makes sense to update that dependency.

**Comment by eigengrau** [comment]
Thanks for letting me know! I keep forgetting to bump the bounds. I guess I could just remove the upper bound, but somehow that feels like cheating…

**Comment by ashkitten** [comment]
yeah no problem :)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
